- src/queries/auth/useLoginMutation.js
- src/queries/auth/useSignInMutation.js
- src/utils/errorMsgHandler.js
- 기존 요청 실패 시 상태코드를 반환하였던 상황에서 디테일한 오류 메세지 출력하도록 하였습니다.
> feat: 로그인/회원가입 실패 시 에러 메세지 출력

- .vscode/settings.json
- package-lock.json
- src/apis/userRelatedAPI.js
- src/queries/auth/useWithdrawl.js
- src/queries/auth/useWithdrawlMutation.js
- useWithdrawl.js에 회원탈퇴 기능을 추가
- 
- 회원탈퇴 실패 시에 발생할 errorHandler 작성 필요
- asap
> feat: 회원탈퇴 기능추가

- .vscode/settings.json
- package-lock.json
- package.json
- src/components/MyPage/ItemList.js
- src/components/MyPage/ItemListCard.js
- src/components/MyPage/index.js
- src/pages/MyPage/MyPage.js
- MyPage의 Inventory의 ItemCard UI 생성했습니다.
- 
- 
-
> feat: ItemListCard 추가

- src/components/MyPage/ItemList.js
- src/components/MyPage/ItemListCard.js
- src/components/MyPage/ProfileBackground/ProfileBackground.js
> Inventory UI

- src/pages/Login/Login.js
> feat:LoginUI생성

- src/pages/Login/Login.js
- src/pages/Register/Register.js
> update Register UI

- src/components/MyPage/InterestedAuctionList.js
- src/components/MyPage/InterestedAuctionListCard.js
- src/components/MyPage/ItemListCard.js
- src/components/MyPage/TabBar.js
> style: 관심 거래 기본 카드 UI 추가;

- src/App.js
- src/pages/MyPage/ItemDetail.js
- itemDetail.js UI 완료했습니다.
- 
- 
-
> FEAT: itemDetail.js 생성 및 UI 작업

- src/apis/productsRelatredAPI.js
- src/components/MyPage/AddItemModal.js
- src/components/MyPage/ItemList.js
- src/components/MyPage/ItemListCard.js
- src/queries/product/useMyProductsQuery.js
- src/utils/statusHandler.js
- get 방식으로 products 뿌리는 로직 추가 및 실제 컴포넌트에 적용
> My items 보는 로직 추가 

- src/App.js
- src/pages/Auction/NewAuction1.js
- src/pages/Auction/NewAuction2.js
- NewAuction UI 작업했습니다.
- 
- 
-
> FEAT: NewAuction.js 생성 및 UI 작업

- src/components/MyPage/ItemDetail/Left_Component.js
- src/components/MyPage/ItemDetail/Right_Component.js
- src/pages/MyPage/ItemDetail.js
> feat: Create ItemDetail_UI

- src/components/MyPage/ItemDetail/Left_Component.js
- src/components/MyPage/ItemDetail/Right_Component.js
- src/pages/MyPage/ItemDetail.js
- 유라씨의 ItemDetail.js UI 코드 리팩토링 완료했습니다.
- 
- 
-
> REFACTOR: ItemDetial.js 코드 리팩토링

- src/components/MyPage/Chat/ChatLists.js
- src/components/MyPage/Chat/InputMessage.js
- src/components/MyPage/Chat/OnChatUserProfile.js
- src/pages/Chat/Chat.js
- Chat.js UI 코드 리팩토링 완료했습니다.
- 
- 
-
> REFACTOR: Chat.js UI코드 리팩토링

- src/pages/AuctionPublish/NewAuction1.js
- src/pages/AuctionPublish/NewAuction2.js
- NewAuction1,2 UI코드 리팩토링 완료했습니다.
- 
- 
-
> New auction refactor

- src/components/Navbar/UserRelatedDropDown.js
- src/pages/Navbar/Navbar.js
> feat: 네브바 UI 작성

- src/components/MyPage/ItemDetail/Left_Component.js
- src/components/MyPage/ItemDetail/Right_Component.js
- src/components/TopRank/Ranking.js
- src/components/TopRank/TopRanker.js
- src/components/TopRank/WeeklyStatus.js
- src/components/TopRank/index.js
- src/pages/Chat/Chat.js
- src/pages/Login/Login.js
- src/pages/Register/Register.js
- src/pages/TopRank/TopRank.js
- Login Register.js 에서 Card 가운데 정렬 및 Input width가 %로 되어 생기던 오류를 수정하였습니다.
> feat: Login, Register Card UI 및 Input width 수정

- src/components/Auction/AuctionDetail/ValidationModal.js
- ValidationModal Figma UI에 맞게 수정하였습니다.
> feat: ValidationModal UI 수정

- src/components/Auction/AuctionDetail/AuctionDetailModal.js
- src/components/Auction/AuctionDetail/AuctionItem.js
- src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
- src/components/MyPage/ItemDetail/ItemInfoContainer.js
- 경매장에서 ItemDetail Modal ItemDetail.js와 연결
> feat: Create ItemDetail Modal

- src/components/Auction/AuctionPublish/AuctionPublishModal.js
- src/components/Auction/AuctionPublish/InventoryItem.js
- src/components/MyPage/ItemDetail/ItemImage.js
- src/components/NewAuction/InfoContainerWithItem.js
- src/components/NewAuction/NewAuctionInput.js
- src/pages/NewAuction/NewAuction.js
- src/themes/theme.js
- New Auction UI Figma에 맞게 수정하였습니다.
> feat: NewAuction UI 수정

- src/components/MyPage/Chat/InputMessage.js
- src/components/MyPage/Chat/MyProfile.js
- src/components/MyPage/Chat/UserEvaluationModal.js
- src/components/Navbar/UserRelatedDropDown.js
- src/pages/Auction/Auction.js
- src/pages/Chat/Chat.js
> style: navbar 수정 및 홈그라운드 수정

- src/components/MyPage/InterestedAuctionList.js
- src/components/MyPage/InterestedAuctionListCard.js
- yarn.lock
- 마이페이지-관심거래 UI 작성
- 관심거래 카드
- pagination
-
- 
-
> feat: 마이페이지-관심거래 UI 작성

- src/components/Navbar/UserRelatedDropDown.js
> chore: dropdownmenu 및 오류수정

- src/components/MyPage/InterestedAuctionListCard.js
- 'InterestedAuctionListCard.js' 수정
- card 배열 수정 _ justify-content: flex-start로 수정
- 
- 
-
> chore: card 배열 justify-content 수정

- src/components/MyPage/InterestedAuctionListCard.js
- src/components/MyPage/MyAuctionList.js
- 마이페이지-내가 올린 경매 UI 작성
- 마이페이지-관심거래의 card margin-righ를 nth(2),(5)로 수정
-> 마이페이지-내가 올린 경매 UI에도 동일하게 반영
- 
- 
-
> feat: 마이페이지-내가 올린 경매 UI 작성

- src/components/TopRank/WeeklyStatus.js
- 명예의 전당-이번 주 신분상승 UI 수정 및 추가
- 수정
- 프로필 아이콘 크기 키우기
- RecentRank(등급 변경 전)와 UserRank(등급 변경 후) 아이콘 정렬 & 그림자 추가
- 추가
- pagination 아이콘 추가  
- 
- 
-
> feat: 명예의전당-이번주 신분상승UI 수정 및 추가

- src/components/Home/HomeAuctionListCard.js
- src/components/MyPage/MyAuctionList.js
- src/pages/Auction/Auction.js
> User info change

- src/components/TopRank/Ranking.js
- src/components/TopRank/TopRanker.js
- src/components/TopRank/WeeklyStatus.js
- 명예의 전당 페이지 - QuestionIcon hover 했을 때 나올 tooltip UI 작성
- 
- 
-
> feat: 명예의전당 물음표 아이콘 tooltip UI

- src/components/MyPage/TransactionHistory.js
- src/pages/Auction/Auction.js
- 경매장 '홈그라운드의 모든 거래' 영역 Pagination 추가
- 
- 
-
> Auction pagination

- src/components/MyPage/TransactionHistory.js
- 마이페이지-히스토리 Pagination 추가
- 
- 
-
> feat: 마이페이지-히스토리 Pagination

- src/components/Auction/AuctionDetail/AuctionDetailModal.js
- src/components/MyPage/ItemDetail/ItemImage.js
- src/components/MyPage/ItemDetail/ItemInfoContainer.js
- AuctionDetail 모달 UI 배열 수정
- SubPic 크기 고정
- 설명란 크기, 배열 조정 
- 
- 
-
> feat: AuctionDetail 모달 UI 배열

- src/components/Auction/AuctionDetail/AuctionItem.js
- src/components/Auction/AuctionDetail/AuctionOtherSuggestion.js
- src/components/Auction/AuctionDetail/MySuggested.js
- src/components/MyPage/ItemListCard.js
- src/components/MyPage/TransactionHistory.js
- src/layouts/WrapContainer.js
- src/pages/Auction/Auction.js
- Auction Detail 페이지 관련하여 Pagenation 위치 수정하였으며, height 짤리는 현상 수정했습니다.
- 관심거래 저장 버튼 UI와 위치 수정하였습니다.
> feat : Auction Detail Reafactor

- src/components/MyPage/AddItemModal.js
- src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
- 마이페이지의 아이템 추가 모달창 UI 리팩토링 완료했습니다.
- 아이템 설명 적는 editor를 textarea로 바꿨고, 아이템 생성 잘 작동합니다.
- 
- 
-
> refactor: 아이템 추가 모달창 UI 리팩토링 완료

- src/components/MyPage/InterestedAuctionList.js
- src/components/MyPage/ItemList.js
- src/components/MyPage/MyAuctionList.js
- src/components/MyPage/TabBar.js
- src/components/MyPage/TransactionHistory.js
- src/components/Shared/AuctionListItem.js
- src/components/TopRank/Ranking.js
- src/components/TopRank/TopRanker.js
- src/components/TopRank/WeeklyStatus.js
- src/pages/Auction/Auction.js
- src/pages/Navbar/Navbar.js
- src/pages/TopRank/TopRank.js
- 마이페이지 > 인벤토리에서 아이템 추가 버튼 디자인 개선
- nav바 상에 링크 호버시에, background color가 이상하게 바뀌는 이슈 수정
- nav바에서 a태그 중첩 오류 수정
- 경매 카드 여백 수정
- 이후 작업자를 위한 TODO 코멘트 추가
- 명예의 전당 페이지 디자인 수정 및 반응형 디자인 적용
- ![image](https://user-images.githubusercontent.com/47373998/184652820-b3dd2392-3910-4b17-b466-dcea523fe973.png)
- 프로필 페이지 탭뷰 좌우 스크롤 적용
- ![image](https://user-images.githubusercontent.com/47373998/184652643-88acb107-d114-4ee9-a38b-05f7ef8c59a8.png)
- ![image](https://user-images.githubusercontent.com/47373998/184652668-0ff9344d-c9b8-4eb7-92ed-9df723d0d923.png)
- ASAP
> 0815 디자인 추가 개선

- src/pages/About/About.js
- abount 페이지
- 컴포넌트 분리할까하다가, 어차피 크게 신경쓰지 않을 파일인 듯해서 그냥 쭉 작성했습니다.
- ASAP
> abount 페이지

- package-lock.json
- src/App.js
- src/components/MyPage/AddItemModal.js
- src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
- src/components/MyPage/ItemDetail/ItemImage.js
- src/components/MyPage/ItemDetail/ItemInfoContainer.js
- src/components/MyPage/ItemDetail/UserInformation.js
- src/components/MyPage/ItemInfoChange/ChangeItemCategory.js
- src/components/MyPage/ItemInfoChange/ChangeItemExtraImage.js
- src/components/MyPage/ItemInfoChange/ChangeItemId.js
- src/components/MyPage/ItemInfoChange/ChangeItemImage.js
- src/components/MyPage/ItemInfoChange/ChangeItemStatus.js
- src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
- src/pages/MyPage/ItemDetail.js
- src/pages/MyPage/ItemInfoChange.js
- yarn.lock
- 아이템 상세 페이지 UI 최종 완료했습니다.
- 아이템 수정 페이지 생성 및 기본 UI 작업했습니다.
-
- 
-
> Item detail&change refactor

- src/components/Auction/AuctionSlider.js
- yarn.lock
- AuctionSlider Item Title overflow ellipsis 처리했습니다.
- AuctionSlider Title에 링크 연결했습니다.
> feat: AuctionSlider 경매 제목 Text Overflow 조정

- src/components/MyPage/TransactionHistory.js
- MyPage History에 아무것도 없을 경우 클릭시 경매장으로 이동하는 link 추가했습니다.
> feat: MyPage History 경매장으로 가는 Link 생성

- src/components/TopRank/TopRanker.js
- TopRank page ToolTip 회색으로 나오는 것 color #000으로 수정했습니다.
> feat: TopRank ToolTip Color 검은색으로 수정

- src/components/Auction/AuctionPublish/AuctionPublishModal.js
- src/components/Auction/AuctionPublish/InventoryItem.js
- src/components/MyPage/AddItemModal.js
- src/components/NewAuction/NewAuctionInput.js
- src/pages/NewAuction/NewAuction.js
- NewAuction 페이지와 아이템 모달창 UI 리팩토링 완료했습니다.
- 
- 
-
> refactor: NewAuction 페이지, 아이템 모달창 UI 리팩토링

- src/components/MyPage/TransactionHistory.js
- 마이페이지 히스토리에서 emptylistplaceholder에 마우스 hover시 텍스트에 밑줄이 생기게 하였습니다.
- 
- 
-
> feat: 마이페이지 히스토리 placeholder 컴포넌트 hover시 텍스트에 밑줄효과 추가

- src/components/Shared/AuctionListItem.js
- src/pages/Auction/Auction.js
- 경매 홈에서 종료된 경매 하트 위치 조정했습니다.
- 경매 홈에서 종료된 경매 hover시 border 생기는거 없앴습니다.
- 경매 홈 페이지 최하단에 padding-bottom 줘서 띄웠습니다.
- 
- 
-
> Auction home refactor

- src/components/Auction/AuctionAuctioneer/DiscardMessageModal.js
- src/components/Auction/AuctionAuctioneer/SelectMessageModal.js
- src/queries/dealing/useCreateDealingMutation.js
- Auctioneer.js 폐기, 선택 버튼 모달창의 UI 리팩토링 했습니다. 
- 전체 화면 너비에 따라 모달창 크기도 반응형으로 처리했습니다.
- 선택 버튼 누르면 경매홈이 아닌 마이페이지의 진행중인 거래로 이동하게끔 수정했습니다.
- 
- 
-
> Auctioneer refactor

- src/components/Auction/AuctionPublish/AuctionPublishModal.js
- src/components/MyPage/Chat/ChatLists.js
- src/components/NewAuction/InfoContainerWithItem.js
- src/pages/NewAuction/NewAuction.js
- New Auction 관련하여 아이템 다시 선택 button 위치를 상향 조정했습니다.
- 카테고리 컨테이너가 반응형으로 변경 전 깨지는 현상 조정했습니다.
> feat: New auction UI

- src/pages/MyPage/ItemDetail.js
- 마이페이지-인벤토리-아이템 상세 페이지 부분
- 아이템명 hover -> Tooltip 보이게끔 추가 
-
- 
-
> feat: 인벤토리 아이템명 hover  추가

- src/components/TopRank/Ranking.js
- src/pages/About/About.js
- src/pages/MyPage/ItemDetail.js
- TopRank 우측 랭킹 component 10등 margin 조정하여 이탈 수정했습니다.
> feat: TopRank 10등 margin 조정

- src/components/Auction/AuctionAuctioneer/ItemDetailContainer.js
- src/components/MyPage/Chat/UserEvaluationModal.js
- src/components/MyPage/Chat/UserInfoDetailModal.js
- src/pages/MyPage/ItemDetail.js
- TopRank 페이지 평가하기, 거래보기 Modal Button height 조정했습니다. 
- 해당 모달 media 이용하여 반응형으로 해놨습니다.
> feat: TopRank 평가하기, 거래보기 Modal UI 수정

- src/components/Home/FilterModal.js
- yarn.lock
- 경매장 홈 필터 높이 및 내부 간격 조정
- <img width="1067" alt="auction-filter-ui 캡처" src="https://user-images.githubusercontent.com/102042966/185512057-7fd58715-50cb-4c00-a020-502053da1784.png">
- 
-
> style: 경매장 홈 필터 높이 및 내부 간격 조정

- src/components/MyPage/AddItemModal.js
- src/components/MyPage/ItemAddForm/ImageDragDrop/styles.js
- src/components/MyPage/ItemInfoChange/ChangeItemCategory.js
- src/components/MyPage/ItemInfoChange/ChangeItemId.js
- src/components/MyPage/ItemInfoChange/ChangeItemImage.js
- src/components/MyPage/ItemInfoChange/ChangeItemStatus.js
- src/components/MyPage/ItemInfoChange/ChangeItemTextarea.js
- src/pages/MyPage/ItemInfoChange.js
- 아이템명 title 말줄임표
- 대표사진 > 새 대표사진 카메라 아이콘 정렬
- 인벤토리 > 아이템 추가 모달의 아이템 설명 label 미세조정
> feat: 아이템 정보 수정

- src/components/Home/FilterModal.js
- 경매장 필터 컨테이너 내부 배열 조정
- <img width="959" alt="경매 필터 배열 조정" src="https://user-images.githubusercontent.com/102042966/185586116-3fd8af89-7c66-4c8a-ae5b-02dfdf915e20.png">
- 
-
> chore: Auction filter 컨테이너 내부 배열 조정

- src/queries/auction/useAuctionsQuery.js
- src/queries/auction/useInterestedAuctionsQuery.js
- src/queries/auction/useMyAuctionQuery.js
- src/queries/auction/useMyProductGroupQuery.js
- src/queries/auction/usePopularAuctionsQuery.js
- src/queries/auction/useProductGroupsQuery.js
- src/queries/auction/useSingleAuctionQuery.js
- src/queries/dealing/useDealingHistoryQuery.js
- src/queries/dealing/useDealingsQuery.js
- src/queries/dealing/useTodayCompletedQuery.js
- src/queries/messages/useMessagesQuery.js
- src/queries/product/useMyProductsQuery.js
- src/queries/product/useSingleProductQuery.js
- src/queries/statistics/useDealingRankingQuery.js
- src/queries/statistics/useMonthlyChampionQuery.js
- src/queries/statistics/useMostProductGroupDealingQuery.js
- src/queries/user/useDealingCountQuery.js
- src/queries/user/useRatingQuery.js
- stale time 증가 이후 인터넷 환경에 대한 반응 개선 
- 참고한 자료 또는 리뷰어가 참고할만한 자료를 적습니다.
- 고민되었거나 리뷰어와 논의하였으면 하는 내용 등을 적습니다.
- 리뷰 완료 희망일을 작성합니다.
> feat: stale time increased

- src/components/Auction/AuctionSlider.js
- src/components/MyPage/InterestedAuctionList.js
- src/components/MyPage/ItemList.js
- src/components/MyPage/TransactionHistory.js
- src/components/Shared/EmptyListPlaceholder.js
- src/components/Shared/ValidationModal.js
- 화살표 아이콘 크기, margin/padding 수정
- <img width="643" alt="image" src="https://user-images.githubusercontent.com/102042966/185619985-c6682542-9724-4a84-b4e0-cee4fdec6965.png">
- 
-
> style: 실시간 인기 경매 화살표 아이콘 수정

- src/components/MyPage/Chat/ChatMsgContainer.js
- src/components/MyPage/TransactionHistory.js
- src/components/Shared/EmptyHistoryPlaceholder.js
- src/pages/Chat/Chat.js
- src/pages/Login/Login.js
- src/pages/Register/Register.js
> chore: 마이페이지 히스토리 수정

- src/components/MyPage/TransactionHistory.js
- 마이페이지-히스토리 우측 컨테이너 margin 조정
-
-
-
> chore: 히스토리 우측 컨테이너 margin 조정
